services:
  - type: web
    name: luxury-detector-app
    env: python
    buildCommand: ""
    startCommand: python luxury-detection-app/app.py
    envVars:
      - key: FLASK_ENV
        value: production
